export 'package:heart_attack_detection_fe/pages/category/Doctor/DoctorModal/index.dart';
export 'package:heart_attack_detection_fe/pages/category/Doctor/index.dart';
export 'package:heart_attack_detection_fe/pages/category/Medicine/index.dart';
export 'package:heart_attack_detection_fe/pages/category/Module/index.dart';
export 'package:heart_attack_detection_fe/pages/category/Prescription/PrescriptionDetail/index.dart';
export 'package:heart_attack_detection_fe/pages/category/Prescription/PrescriptionModal/index.dart';
export 'package:heart_attack_detection_fe/pages/category/Prescription/index.dart';
export 'package:heart_attack_detection_fe/pages/notFound/notFound.dart';
export 'package:heart_attack_detection_fe/pages/doctor/PatientRecord/index.dart';